### ISSUE TITLE
Remote I/O Error FocuserExample.py

### ISSUE THREAD

**Issue by cobba83** [ArduCAM/PTZ-Camera-Controller#5]
Hi,

i just tried to use the given examples and get the following stacktrace:

> pi@raspberrypi:~/PTZ-Camera-Controller/pyCode $ sudo python FocuserExample.py
Traceback (most recent call last):
  File "FocuserExample.py", line 233, in <module>
    main()
  File "FocuserExample.py", line 225, in main
    curses.wrapper(draw_menu,camera)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "FocuserExample.py", line 206, in draw_menu
    RenderMiddleText(stdscr,k,focuser)
  File "FocuserExample.py", line 84, in RenderMiddleText
    focus_value = "Focus    : {}".format(focuser.get(Focuser.OPT_FOCUS))[:width-1]
  File "/home/pi/PTZ-Camera-Controller/pyCode/Focuser.py", line 120, in get
    self.waitingForFree()
  File "/home/pi/PTZ-Camera-Controller/pyCode/Focuser.py", line 69, in waitingForFree
    while self.isBusy() and count < (5 / 0.01):
  File "/home/pi/PTZ-Camera-Controller/pyCode/Focuser.py", line 65, in isBusy
    return self.read(self.CHIP_I2C_ADDR,self.BUSY_REG_ADDR) != 0
  File "/home/pi/PTZ-Camera-Controller/pyCode/Focuser.py", line 56, in read
    value = self.bus.read_word_data(chip_addr,reg_addr)
IOError: [Errno 121] Remote I/O error`

I'm using a Raspberry Pi Model 3 B with Rasbian OS 10 Buster.

Hope you can help me solving this problem.

**Comment by crand1213** [comment]
Hello, I am having the exact same issue using Raspberry Pi Model 4 B.
using any of the FocuserExample.py or AutofocusExample.py gives me the same error.

configuration:
Raspberry pi 4 b 8Gb
Raspian buster 
Camera was purchased and delivered Dec 2, 2020.

camera is enabled in config
i2c is enabled in config.
raspivid and raspistill produce images and video.
Using VNC to view desktop

Will be seeking refund if not rectified.


![PiError1](https://user-images.githubusercontent.com/75600797/101599421-97466d80-39ae-11eb-95fa-ed4ba1cb35b2.PNG)
![PiError2](https://user-images.githubusercontent.com/75600797/101599426-99103100-39ae-11eb-88fe-ddae68809ed3.PNG)

**Comment by mifi** [comment]
Anyone found a solution?

**Comment by devinross** [comment]
I'm having the same issue 2 years later

**Comment by th-walker** [comment]
I am having the same problem. Anyone able to resolve it?

**Comment by AgribotGit** [comment]
I am having the same problem. Arducam ... Please help resolve this common detect, thanks.

**Comment by Te12944265-AMAHA** [comment]
I'm having the same problem. On Trixie OS
